const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const url = process.env.PHOENIX_TEST_URL || 'http://127.0.0.1:4173/Hyrox-Trainer/';
const output = path.resolve('../qa');
fs.mkdirSync(output, { recursive: true });
(async () => {
  const browser = await chromium.launch({ channel: process.env.PHOENIX_BROWSER || 'chrome', headless: true });
  const context = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1, acceptDownloads: true });
  const page = await context.newPage();
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  const response = await page.goto(url); assert.equal(response.status(), 200);
  await page.waitForFunction(() => document.querySelector('#offline-status').textContent.startsWith('Offline ready'));
  assert.equal(await page.locator('[data-day]').count(), 147);
  assert.equal(await page.locator('.week').count(), 21);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, 'mobile overflow');
  await page.screenshot({ path: path.join(output, 'mobile.png'), fullPage: false });
  await page.locator('#week-1').evaluate(w => w.open = true);
  const check = page.locator('[data-day="2026-10-05"]');
  await check.check(); assert.equal(await page.locator('#done-count').innerText(), '1');
  await page.reload(); await page.locator('#week-1').evaluate(w => w.open = true);
  assert.equal(await check.isChecked(), true, 'persist after reload');
  const downloadPromise = page.waitForEvent('download'); await page.locator('#export').click();
  const download = await downloadPromise; const backup = path.join(output, 'backup.json'); await download.saveAs(backup);
  assert.deepEqual(JSON.parse(fs.readFileSync(backup)).completed, ['2026-10-05']);
  page.once('dialog', d => d.accept()); await page.locator('#reset').click(); assert.equal(await page.locator('#done-count').innerText(), '0');
  await page.locator('#import').setInputFiles(backup); await page.waitForFunction(() => document.querySelector('#done-count').textContent === '1');
  await page.locator('#import').setInputFiles({ name: 'bad.json', mimeType: 'application/json', buffer: Buffer.from('{"schemaVersion":1,"completed":["bad-day"]}') });
  await page.waitForFunction(() => document.querySelector('#backup-status').textContent.includes('could not be read'));
  assert.equal(await page.locator('#done-count').innerText(), '1');
  const second = await context.newPage(); await second.goto(url); await second.locator('#week-1').evaluate(w => w.open = true);
  await second.locator('[data-day="2026-10-06"]').check(); await page.waitForFunction(() => document.querySelector('#done-count').textContent === '2');
  await second.close();
  await page.locator('#today-link').click(); assert.equal(await page.locator('.today').evaluate(el => el.closest('details').open), true);
  assert.ok(await page.evaluate(() => navigator.serviceWorker.controller !== null), 'worker controlling page');
  await context.setOffline(true); await page.reload(); assert.equal(await page.locator('.day').count(), 147);
  await page.locator('#week-1').evaluate(w => w.open = true); await page.locator('[data-day="2026-10-07"]').check();
  await page.reload(); assert.equal(await page.locator('#done-count').innerText(), '3');
  assert.equal(await page.evaluate(() => getComputedStyle(document.querySelector('.race-strip')).backgroundColor), 'rgb(25, 44, 38)', 'offline CSS');
  await context.setOffline(false);
  await page.setViewportSize({width:1440,height:1000}); await page.screenshot({path:path.join(output,'desktop.png')});
  const fallback = await browser.newContext({ javaScriptEnabled:false, viewport:{width:375,height:812}, serviceWorkers:'block' });
  const fallbackPage = await fallback.newPage(); await fallbackPage.goto(url);
  await fallbackPage.locator('#week-21 summary').click();
  assert.equal(await fallbackPage.locator('#day-2027-02-28 h3').innerText(),'Phoenix race day');
  assert.equal(await fallbackPage.locator('#day-2027-02-28').isVisible(),true);
  await fallbackPage.locator('[data-day="2027-02-28"]').check();
  assert.equal(await fallbackPage.locator('[data-day="2027-02-28"]').isChecked(),true);
  assert.equal(await fallbackPage.locator('noscript').isVisible(),true);
  assert.equal(await fallbackPage.evaluate(() => document.documentElement.scrollWidth<=innerWidth),true);
  await fallback.close();
  const blocked=await browser.newContext({viewport:{width:320,height:700}});
  await blocked.addInitScript(()=>{Object.defineProperty(window,'localStorage',{get(){throw new DOMException('blocked','SecurityError')}})});
  const blockedPage=await blocked.newPage();await blockedPage.goto(url);
  await blockedPage.locator('#week-1').evaluate(w=>w.open=true);
  await blockedPage.locator('[data-day="2026-10-05"]').check();
  assert.equal(await blockedPage.locator('#done-count').innerText(),'1');
  assert.ok((await blockedPage.locator('#storage-status').innerText()).includes('could not save'));
  assert.equal(await blockedPage.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'320px overflow');
  await blocked.close(); assert.deepEqual(errors,[]);
  await browser.close(); console.log('PASS: mobile + desktop layout, 147 workouts, saved checkoffs, backup/restore, corrupt backup, cross-tab sync, offline reload/checkoff, no-JS fallback and unavailable storage.');
})().catch(e=>{console.error(e);process.exit(1)});
