const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const url=process.env.HYROX_TEST_URL||'http://127.0.0.1:4173/Hyrox-Trainer/';
const output=path.resolve('../qa');fs.mkdirSync(output,{recursive:true});
function freezeDate(context,iso='2026-10-08T12:00:00'){
  return context.addInitScript(iso=>{const NativeDate=Date;class TestDate extends NativeDate{constructor(...args){super(...(args.length?args:[iso]));}static now(){return new NativeDate(iso).valueOf();}}window.Date=TestDate;},iso);
}
(async()=>{
  const browser=await chromium.launch({channel:process.env.HYROX_BROWSER||'chrome',headless:true});
  const context=await browser.newContext({viewport:{width:390,height:844},acceptDownloads:true});
  await freezeDate(context);
  const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
  assert.equal((await page.goto(url)).status(),200);
  await page.waitForSelector('#setup:not([hidden])');
  assert.equal(await page.title(),'HYROX Trainer');assert.equal(await page.locator('#trainer').isVisible(),false);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.screenshot({path:path.join(output,'setup.png')});
  await page.locator('#race-date').fill('2027-02-28');await page.locator('#setup-form button').click();
  await page.waitForSelector('#trainer:not([hidden])');
  assert.equal(await page.locator('#day-number').innerText(),'DAY 1');assert.equal(await page.locator('#today-workout h2').innerText(),'Strength foundations');
  assert.equal(await page.locator('#countdown').innerText(),'143');
  assert.equal(await page.locator('#personal-plan [data-workout]').count(),144);
  assert.equal(await page.locator('#today-workout [data-task]').count(),8);
  await page.screenshot({path:path.join(output,'today.png'),fullPage:false});
  await page.locator('#today-workout [data-task="0"]').check();await page.reload();
  await page.waitForSelector('#trainer:not([hidden])');
  assert.equal(await page.locator('#today-workout [data-task="0"]').isChecked(),true);
  assert.equal(await page.locator('#day-number').innerText(),'DAY 1');
  const taskCount=await page.locator('#today-workout [data-task]').count();
  for(let i=1;i<taskCount;i++)await page.locator(`#today-workout [data-task="${i}"]`).check();
  assert.equal(await page.locator('#wins-count').innerText(),'1');assert.equal(await page.locator('#today-title').innerText(),'Win collected.');
  assert.ok((await page.locator('#celebration').innerText()).includes('First win'));
  await page.locator('#today-workout [data-task="1"]').uncheck();assert.equal(await page.locator('#wins-count').innerText(),'0');
  await page.locator('#today-workout [data-complete]').check();assert.equal(await page.locator('#wins-count').innerText(),'1');
  await page.locator('#view-plan').click();assert.equal(await page.locator('#today-view').isVisible(),false);
  assert.equal(await page.locator('#personal-plan [data-complete="2026-10-08"]').isChecked(),true);
  await page.locator('#view-today').click();await page.locator('#settings>summary').click();
  const promise=page.waitForEvent('download');await page.locator('#export').click();const download=await promise;
  const backup=path.join(output,'personal-backup.json');await download.saveAs(backup);
  const state=JSON.parse(fs.readFileSync(backup));assert.equal(state.start,'2026-10-08');assert.equal(state.race,'2027-02-28');assert.deepEqual(state.completed,['2026-10-08']);
  await page.locator('#change-date').fill('2027-03-14');await page.locator('#change-form button').click();
  assert.equal(await page.locator('#countdown').innerText(),'157');assert.equal(await page.locator('#day-number').innerText(),'DAY 1');
  assert.equal(await page.locator('#wins-count').innerText(),'1');
  page.once('dialog',d=>d.accept());await page.locator('#import').setInputFiles(backup);await page.waitForFunction(()=>document.querySelector('#countdown').textContent==='143');
  await page.locator('#import').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"schemaVersion":2,"start":"2026-10-08","race":"2027-02-28","completed":["bad"],"tasks":{}}')});
  await page.waitForFunction(()=>document.querySelector('#backup-status').textContent.includes('Nothing was changed'));assert.equal(await page.locator('#wins-count').innerText(),'1');
  const second=await context.newPage();await second.goto(url);await second.waitForSelector('#trainer:not([hidden])');
  await second.locator('#today-workout [data-complete]').uncheck();await page.waitForFunction(()=>document.querySelector('#wins-count').textContent==='0');await second.close();
  await page.waitForFunction(()=>document.querySelector('#offline-status').textContent.startsWith('Offline ready'));
  await page.reload();await page.waitForSelector('#trainer:not([hidden])');assert.ok(await page.evaluate(()=>navigator.serviceWorker.controller));
  await context.setOffline(true);await page.reload();await page.waitForSelector('#trainer:not([hidden])');
  await page.locator('#today-workout [data-complete]').check();await page.reload();await page.waitForSelector('#trainer:not([hidden])');assert.equal(await page.locator('#wins-count').innerText(),'1');
  await context.setOffline(false);
  // A later visit moves today forward while leaving the start date unchanged.
  await page.addInitScript(()=>{const NativeDate=Date;class LaterDate extends NativeDate{constructor(...args){super(...(args.length?args:['2026-10-09T12:00:00']));}static now(){return new NativeDate('2026-10-09T12:00:00').valueOf();}}window.Date=LaterDate;});
  await page.reload();await page.waitForSelector('#trainer:not([hidden])');assert.equal(await page.locator('#day-number').innerText(),'DAY 2');assert.equal(await page.locator('#today-workout h2').innerText(),'Easy run / walk');
  assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('hyrox-trainer-v2')).start),'2026-10-08');
  await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:path.join(output,'desktop.png')});
  const short=await browser.newContext({viewport:{width:320,height:700},reducedMotion:'reduce'});await freezeDate(short);const shortPage=await short.newPage();await shortPage.goto(url);await shortPage.waitForSelector('#setup:not([hidden])');
  await shortPage.locator('#race-date').fill('2026-10-10');await shortPage.locator('#setup-form button').click();await shortPage.waitForSelector('#trainer:not([hidden])');
  assert.equal(await shortPage.locator('#personal-plan [data-workout]').count(),3);assert.equal(await shortPage.locator('#timeline-note').isVisible(),true);
  assert.equal(await shortPage.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'320px layout');
  assert.equal(await shortPage.locator('#personal-plan [data-workout="2026-10-09"] h2').innerText(),'Rest + prepare');await short.close();
  const blocked=await browser.newContext({viewport:{width:375,height:812}});await freezeDate(blocked);await blocked.addInitScript(()=>Object.defineProperty(window,'localStorage',{get(){throw new DOMException('blocked','SecurityError');}}));
  const blockedPage=await blocked.newPage();await blockedPage.goto(url);await blockedPage.waitForSelector('#setup:not([hidden])');await blockedPage.locator('#race-date').fill('2027-02-28');await blockedPage.locator('#setup-form button').click();await blockedPage.waitForSelector('#trainer:not([hidden])');
  await blockedPage.locator('#today-workout [data-complete]').check();assert.equal(await blockedPage.locator('#wins-count').innerText(),'1');assert.ok((await blockedPage.locator('#storage-status').innerText()).includes('unavailable'));await blocked.close();
  const fallback=await browser.newContext({javaScriptEnabled:false,serviceWorkers:'block',viewport:{width:375,height:812}}),fp=await fallback.newPage();await fp.goto(url);
  await fp.locator('#fallback>details>summary').click();await fp.locator('#week-21>summary').click();
  assert.equal(await fp.locator('#day-2027-02-28').isVisible(),true);await fp.locator('[data-day="2027-02-28"]').check();assert.equal(await fp.locator('[data-day="2027-02-28"]').isChecked(),true);
  assert.equal(await fp.locator('noscript').isVisible(),true);await fp.locator('#guide>summary').click();assert.equal(await fp.locator('#stations table').isVisible(),true);await fallback.close();
  assert.deepEqual(errors,[]);await browser.close();
  console.log('PASS: race setup, first-day anchoring, variable-length plan, per-exercise + session checkoffs, celebrations, date changes, backup/restore, cross-tab sync, offline personal plan, short timeline, 320px layout, unavailable storage and no-JS starter.');
})().catch(e=>{console.error(e);process.exit(1);});
