import fs from 'node:fs';
import { plan, START, RACE } from './plan.mjs';
fs.mkdirSync('docs',{recursive:true});
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=d=>new Date(d+'T12:00:00Z').toLocaleDateString('en-US',{month:'short',day:'numeric',timeZone:'UTC'});
const dayName=d=>new Date(d+'T12:00:00Z').toLocaleDateString('en-US',{weekday:'long',timeZone:'UTC'});
const html=`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"><title>Phoenix · Your first HYROX</title><meta name="description" content="Your 21-week beginner HYROX Phoenix plan. Daily workouts, station guide, offline access and progress saved on your device."><meta name="theme-color" content="#192c26"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-status-bar-style" content="default"><meta name="apple-mobile-web-app-title" content="Phoenix"><link rel="manifest" href="./manifest.webmanifest"><link rel="icon" href="./icon.svg" type="image/svg+xml"><link rel="apple-touch-icon" href="./icons/apple-touch-icon.png"><link rel="stylesheet" href="./style.css"><script src="./app.js" defer></script></head>
<body><a class="skip" href="#plan">Skip to workouts</a>
<header class="top"><a href="#" class="brand" aria-label="Phoenix training home"><span class="mark" aria-hidden="true">P<span>↗</span></span><span>PHOENIX<span class="subbrand">THE FIRST FINISH</span></span></a><span class="season">26 / 27<br><small>BEGINNER PLAN</small></span></header>
<main>
<section class="intro" aria-labelledby="title"><div class="eyebrow"><span class="dot"></span> YOUR FIRST HYROX · PHOENIX, AZ</div><h1 id="title">One day.<br>One step <em>closer.</em></h1><p class="lede">A steady build to the start line.<br>21 weeks. Your pace. Your first finish.</p><div class="race-strip"><div><span class="label">RACE TARGET</span><strong>FEB 28, 2027</strong></div><div class="countdown"><strong id="countdown">${RACE}</strong><span id="countdown-label">target date</span></div><span class="race-arrow" aria-hidden="true">↗</span></div></section>
<section class="daily-focus" aria-labelledby="daily-title"><div><span class="eyebrow" id="daily-date">START HERE · OCT 5</span><h2 id="daily-title">Strength foundations</h2><p id="daily-meta">Strength · 40–50 min</p></div><a class="daily-action" id="daily-link" href="#day-2026-10-05">View session <span aria-hidden="true">↗</span></a></section>
<section class="progress-panel" aria-label="Your training progress"><div><span class="label">YOUR CONSISTENCY</span><p><strong id="done-count">0</strong> <span>/ 147 days checked</span></p></div><span class="progress-pct" id="progress-pct">0%</span><progress id="progress" value="0" max="147" aria-label="Days completed">0 / 147</progress><p id="storage-status" class="fine" role="status">Checkoffs save on this device when JavaScript and browser storage are available.</p></section>
<nav class="tabs" aria-label="Training sections"><a href="#plan">Training plan <span>↘</span></a><a href="#stations">Station guide</a><a href="#install">Save to phone</a></nav>
<section id="plan" class="section" aria-labelledby="plan-title"><div class="section-heading"><div><span class="eyebrow">THE DAILY WORK</span><h2 id="plan-title">Your training plan</h2></div><a href="#week-1" id="today-link" class="pill">Go to today <span>↗</span></a></div>
<p class="section-note">Oct 5, 2026 – Feb 28, 2027 · Tap a week to see every session.</p><noscript><p class="notice">All 147 workouts and the station guide work without JavaScript. Checkboxes are temporary; saving progress, the countdown and offline installation require JavaScript. Use your browser’s print option for a paper log.</p></noscript>
<div class="week-list">${plan.map(w=>`<details class="week" id="week-${w.number}" ${w.number===1?'open':''}><summary><span class="week-no">${String(w.number).padStart(2,'0')}</span><span class="week-info"><span class="phase">${esc(w.phase)}</span><strong>${esc(w.name)}</strong><span class="week-dates">${fmt(w.start)} – ${fmt(w.end)}</span></span><span class="week-count" data-week-count="${w.number}">0/7</span><span class="chevron" aria-hidden="true">+</span></summary><div class="week-body">${w.days.map(d=>`<article class="day" id="day-${d.id}" data-date="${d.date}" data-kind="${d.kind}"><div class="day-header"><label class="check-label"><input type="checkbox" data-day="${d.id}" aria-label="Complete ${esc(dayName(d.date))}, ${fmt(d.date)}: ${esc(d.title)}"><span class="check-visual" aria-hidden="true"></span></label><div class="day-heading"><p class="day-date">${dayName(d.date)} · ${fmt(d.date)}</p><h3>${esc(d.title)}</h3><div class="session-meta"><span class="tag">${esc(d.kind)}</span><span>${esc(d.duration)}</span></div></div></div><ol class="steps">${d.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol></article>`).join('')}</div></details>`).join('')}</div></section>
<section class="section" id="how"><span class="eyebrow">START HERE</span><h2>Consistency beats intensity.</h2><div class="guidance-grid"><div><h3>Make it your level</h3><p>Designed as a starting plan for a generally healthy beginner who can brisk-walk 30 minutes. Run/walk is welcome. Repeat a week or reduce volume if you are not recovering. Don’t cram missed sessions into the next day.</p></div><div><h3>Find the right effort</h3><p>RPE is effort out of 10. Easy: 3–4, full sentences. Steady: 5–6, short sentences. Strength: leave 2–3 good reps in reserve. Stop if pain changes your movement; chest pain, faintness or unusual breathlessness need prompt medical attention.</p></div><div><h3>Recover to progress</h3><p>Thursday is full rest. Sunday is optional recovery. Weeks 4, 8, 12 and 16 reduce work; weeks 20–21 taper. Sleep, familiar meals and normal hydration support the training. Get individual guidance if you have an injury or health condition.</p></div></div><p class="fine">This is an original general beginner plan created for this app from the requested schedule, not a recovered coach-authored plan or an official HYROX program. Five training days per week; scale them to your starting fitness.</p></section>
<section id="stations" class="section" aria-labelledby="station-title"><div class="section-heading"><div><span class="eyebrow">KNOW THE COURSE</span><h2 id="station-title">8 runs. 8 stations.</h2></div><span class="outline-label">IN THIS ORDER</span></div><p class="section-note">Run 1 km before <strong>every</strong> station. Total: 8 km running. Loads below are for Singles, in kilograms; sled loads include the sled.</p>
<div class="station-grid">${[
['SkiErg','1,000 m','Long pulls, relaxed recovery. Keep your feet on the platform and get the judge’s confirmation before leaving.'],
['Sled push','50 m','4 × 12.5 m. Small steps, steady pressure. Move the entire sled beyond the line before turning.'],
['Sled pull','50 m','4 × 12.5 m. Stay inside your assigned box. Keep rope clear; move the entire sled past the line.'],
['Burpee broad jumps','80 m','Chest touches the floor. Jump forward with both feet taking off and landing together; follow the marked lane.'],
['Row','1,000 m','Legs, body, arms; reverse on recovery. Use a sustainable stroke rate and confirm the full distance.'],
['Farmers carry','200 m','Carry two kettlebells by your sides. You may put them down to rest; don’t gain distance without them.'],
['Sandbag lunges','100 m','Bag across both shoulders. Rear knee touches the floor; extend hips and knees fully at the top.'],
['Wall balls','100 reps','Squat below parallel, then hit the correct target. Break into manageable sets and listen for no-reps.'],
].map((s,i)=>`<article class="station"><div class="station-top"><span>${String(i+1).padStart(2,'0')}</span><span>${s[1]}</span></div><h3>${s[0]}</h3><p>${s[2]}</p></article>`).join('')}</div>
<h3 class="table-title">Know your division’s load</h3><div class="table-scroll" tabindex="0" role="region" aria-label="Singles race load table; scroll horizontally"><table><thead><tr><th scope="col">Station</th><th scope="col">Women Open</th><th scope="col">Men Open</th><th scope="col">Women Pro</th><th scope="col">Men Pro</th></tr></thead><tbody><tr><th scope="row">Sled push</th><td>102 kg</td><td>152 kg</td><td>152 kg</td><td>202 kg</td></tr><tr><th scope="row">Sled pull</th><td>78 kg</td><td>103 kg</td><td>103 kg</td><td>153 kg</td></tr><tr><th scope="row">Farmers carry</th><td>2 × 16 kg</td><td>2 × 24 kg</td><td>2 × 24 kg</td><td>2 × 32 kg</td></tr><tr><th scope="row">Sandbag</th><td>10 kg</td><td>20 kg</td><td>20 kg</td><td>30 kg</td></tr><tr><th scope="row">Wall ball</th><td>4 kg</td><td>6 kg</td><td>6 kg</td><td>9 kg</td></tr><tr><th scope="row">Target height</th><td>2.70 m</td><td>3.00 m</td><td>2.70 m</td><td>3.00 m</td></tr></tbody></table></div><p class="fine">Verified against the <a href="https://maintain.hyrox.com/rulebooks/HYROX_RulebookSingles_EN.pdf">official Singles 2026/27 rulebook</a> on Oct 8, 2026. These are race loads, not required beginner training loads. Doubles and Relay have different rules. Check the official rules and your registered division before racing.</p></section>
<section class="install section" id="install"><span class="eyebrow">KEEP YOUR PLAN CLOSE</span><h2>A little space<br>on your home screen.</h2><p>On iPhone, open this site in <strong>Safari</strong>, tap <strong>Share</strong>, then <strong>Add to Home Screen</strong>. If available, leave “Open as Web App” enabled and tap Add.</p><p>On Android, use your browser’s <strong>Install app</strong> or <strong>Add to Home screen</strong> option.</p><button id="install-button" hidden>Install Phoenix ↗</button><p class="fine" id="offline-status" role="status">Open once online to prepare offline access. Keep this page open until the offline-ready message appears.</p><p class="fine">Checkoffs are private and stay in this browser on this device. Home-screen apps may use separate storage on iOS. Clearing site data removes progress; use the backup controls below before switching browsers or devices.</p><div class="backup-controls" id="backup-controls" hidden><button id="export">Back up progress ↓</button><label class="button" for="import">Restore backup ↑</label><input id="import" type="file" accept="application/json,.json" class="file-input"><button id="reset" class="quiet">Reset checkoffs</button></div><p id="backup-status" class="fine" role="status"></p></section>
<footer><span class="brand-text">PHOENIX ↗</span><p>Built for your first finish.<br><a href="https://hyrox.com/event/inbody-hyrox-phoenix-26-27/">Official Phoenix event</a> · Feb 25–28, 2027<br>Your actual race day and wave time come from your ticket.</p><p class="fine">Independent training companion. Not affiliated with HYROX.<br><a href="https://github.com/GithunYd/Hyrox-Trainer">Source & updates</a></p></footer>
</main></body></html>`;
fs.writeFileSync('docs/index.html',html);
fs.writeFileSync('docs/plan.json',JSON.stringify({schemaVersion:1,start:START,race:RACE,weeks:plan},null,2)+'\n');
fs.writeFileSync('docs/manifest.webmanifest',JSON.stringify({id:'./',name:'Phoenix · Your first HYROX',short_name:'Phoenix',description:'21-week beginner HYROX plan with private device-local progress.',lang:'en',start_url:'./',scope:'./',display:'standalone',background_color:'#f6f4ec',theme_color:'#192c26',icons:[{src:'./icons/icon-192.png',sizes:'192x192',type:'image/png',purpose:'any'},{src:'./icons/icon-512.png',sizes:'512x512',type:'image/png',purpose:'any maskable'}]},null,2));
console.log(`Built ${plan.length} weeks / ${plan.flatMap(w=>w.days).length} days, ${START} to ${RACE}.`);
