import fs from 'node:fs';
import { plan } from './plan.mjs';
fs.mkdirSync('docs',{recursive:true});
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>HYROX Trainer</title><meta name="description" content="Your race date. Your daily plan. Start today, check off your workouts and build toward your first HYROX."><meta name="theme-color" content="#192c26"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-title" content="HYROX Trainer"><link rel="manifest" href="./manifest.webmanifest"><link rel="icon" href="./icon.svg" type="image/svg+xml"><link rel="apple-touch-icon" href="./icons/apple-touch-icon.png"><link rel="stylesheet" href="./style.css"><script src="./app.js" type="module"></script></head><body><a class="skip" href="#main">Skip to training</a><header class="top"><a class="brand" href="#main"><span class="mark" aria-hidden="true">H↗</span>HYROX TRAINER</a><span class="top-note">ONE SESSION AT A TIME</span></header><main id="main">
<section id="setup" class="setup" hidden><span class="eyebrow">YOUR FIRST FINISH STARTS HERE</span><h1>When’s your<br><em>HYROX?</em></h1><p>Pick your race date. Day one is the day you first open the app. We’ll build your daily plan from there.</p><form id="setup-form"><label for="race-date">Your race date</label><input type="date" id="race-date" required><button type="submit">Build my plan <span aria-hidden="true">↗</span></button><p id="setup-error" class="fine" role="alert"></p></form><p class="fine">A general beginner plan, built around the time you have. Easy progress, regular recovery and a lighter race week.</p></section>
<div id="trainer" hidden><div class="race-bar"><span id="race-summary"></span><strong><span id="countdown"></span> <span id="countdown-label">days to go</span></strong></div><nav class="view-tabs" aria-label="Your training"><button id="view-today" class="active" aria-pressed="true">Today</button><button id="view-plan" aria-pressed="false">Full plan</button></nav><p id="timeline-note" class="notice" hidden></p><section id="today-view"><div class="today-heading"><div><span id="today-date" class="eyebrow"></span><h1 id="today-title">Your next win.</h1></div><span id="day-number" class="day-number"></span></div><div id="today-workout"></div><div class="wins" aria-label="Your progress"><div><strong id="wins-count">0</strong><span>days completed</span></div><div><strong id="rhythm-count">0</strong><span>day rhythm</span></div><div><strong id="week-count">0/0</strong><span>training this week</span></div></div><div class="week-dots" id="week-dots" aria-label="This week"></div><p class="reward-note" id="reward-note">Your first checkmark is waiting. Small steps count.</p></section><section id="plan-view" hidden><div class="section-heading"><h2>Your road to race day</h2><span id="plan-length" class="fine"></span></div><p class="fine">Start where you are. Missed a day? Continue at your pace; don’t double up.</p><div id="personal-plan"></div></section><p id="storage-status" class="fine" role="status"></p></div>
<div id="fallback"><p class="notice">Race-date setup is loading. If it is unavailable, the starter workouts below still work.</p><noscript><p class="notice">Personal dates and saved progress require JavaScript. You can still read the starter plan, check boxes for this visit, and use the station guide.</p></noscript><details class="resource"><summary>21-week starter plan <span>+</span></summary><p class="fine">Sample training sequence. Use your race date to create a dated plan when app setup is available.</p>${plan.map(w=>`<details class="week" id="week-${w.number}" ${w.number===1?'open':''}><summary><span class="week-no">${w.number}</span><span class="week-info"><span class="phase">${esc(w.phase)}</span><strong>${esc(w.name)}</strong></span><span>+</span></summary><div class="week-body">${w.days.map((d,j)=>`<article class="day" id="day-${d.id}"><label><input type="checkbox" data-day="${d.id}" aria-label="Complete starter day ${(w.number-1)*7+j+1}"> Day ${(w.number-1)*7+j+1}</label><h3>${esc(d.title)}</h3><p class="fine">${esc(d.kind)} · ${esc(d.duration)}</p><ol class="steps">${d.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol></article>`).join('')}</div></details>`).join('')}</details></div>
<details class="resource" id="guide"><summary>Station guide <span>+</span></summary><section id="stations" class="section" aria-labelledby="station-title"><div class="section-heading"><div><span class="eyebrow">KNOW THE COURSE</span><h2 id="station-title">8 runs. 8 stations.</h2></div><span class="outline-label">IN THIS ORDER</span></div><p class="section-note">Run 1 km before <strong>every</strong> station. Total: 8 km running. Loads below are for Singles, in kilograms; sled loads include the sled.</p>
<div class="station-grid">${[
['SkiErg','1,000 m','Long pulls, relaxed recovery. Keep your feet on the platform and get the judge’s confirmation before leaving.'],
['Sled push','50 m','4 × 12.5 m. Small steps, steady pressure. Move the entire sled beyond the line before turning.'],
['Sled pull','50 m','4 × 12.5 m. Stay inside your assigned box. Keep rope clear; move the entire sled past the line.'],
['Burpee broad jumps','80 m','Chest touches the floor. Jump forward with both feet taking off and landing together; follow the marked lane.'],
['Row','1,000 m','Legs, body, arms; reverse on recovery. Use a sustainable stroke rate and confirm the full distance.'],
['Farmers carry','200 m','Carry two kettlebells by your sides. You may put them down to rest; don’t gain distance without them.'],
['Sandbag lunges','100 m','Bag across both shoulders. Rear knee touches the floor; extend hips and knees fully at the top.'],
['Wall balls','100 reps','Squat below parallel, then hit the correct target. Break into manageable sets and listen for no-reps.'],
].map((s,i)=>`<article class="station"><div class="station-top"><span>${String(i+1).padStart(2,'0')}</span><span>${s[1]}</span></div><h3>${s[0]}</h3><p>${s[2]}</p></article>`).join('')}</div>
<h3 class="table-title">Know your division’s load</h3><div class="table-scroll" tabindex="0" role="region" aria-label="Singles race load table; scroll horizontally"><table><thead><tr><th scope="col">Station</th><th scope="col">Women Open</th><th scope="col">Men Open</th><th scope="col">Women Pro</th><th scope="col">Men Pro</th></tr></thead><tbody><tr><th scope="row">Sled push</th><td>102 kg</td><td>152 kg</td><td>152 kg</td><td>202 kg</td></tr><tr><th scope="row">Sled pull</th><td>78 kg</td><td>103 kg</td><td>103 kg</td><td>153 kg</td></tr><tr><th scope="row">Farmers carry</th><td>2 × 16 kg</td><td>2 × 24 kg</td><td>2 × 24 kg</td><td>2 × 32 kg</td></tr><tr><th scope="row">Sandbag</th><td>10 kg</td><td>20 kg</td><td>20 kg</td><td>30 kg</td></tr><tr><th scope="row">Wall ball</th><td>4 kg</td><td>6 kg</td><td>6 kg</td><td>9 kg</td></tr><tr><th scope="row">Target height</th><td>2.70 m</td><td>3.00 m</td><td>2.70 m</td><td>3.00 m</td></tr></tbody></table></div><p class="fine">Verified against the <a href="https://maintain.hyrox.com/rulebooks/HYROX_RulebookSingles_EN.pdf">official Singles 2026/27 rulebook</a> on Oct 8, 2026. These are race loads, not required beginner training loads. Doubles and Relay have different rules. Check the official rules and your registered division before racing.</p></section>
</details><details class="resource" id="settings"><summary>My plan & settings <span>+</span></summary><div class="settings-body"><form id="change-form" hidden><label for="change-date">Race date</label><input type="date" id="change-date" required><p class="fine">Keep your original first day. Changing the race date can change future workouts; completed days are kept, and individual tasks are kept only when their workout is unchanged.</p><button type="submit">Update race date</button><p id="change-status" class="fine" role="status"></p></form><div id="backup-controls" hidden><button id="export">Back up my plan ↓</button><label class="button" for="import">Restore backup ↑</label><input id="import" type="file" accept="application/json,.json"><button id="legacy-export" hidden>Back up previous plan</button><button id="reset" class="quiet">Start a new plan</button><p id="backup-status" class="fine" role="status"></p></div><details class="mini-resource"><summary>How to use your plan</summary><p class="fine">Easy effort: full sentences, RPE 3–4 out of 10. Steady: short sentences, RPE 5–6. Lift with 2–3 good reps left. Start lighter and use walk breaks. Day 4 of each regular training week is rest; day 7 is optional recovery. Recovery weeks reduce the work and race week stays light.</p><p class="fine">This plan assumes you can comfortably brisk-walk 30 minutes. Repeat or reduce sessions as needed. Short plans don’t compress months of training or guarantee race readiness. Stop if pain changes your movement; seek prompt help for chest pain, faintness or unusual breathlessness. Get individual advice for injuries or health conditions.</p></details></div></details><details class="resource" id="install"><summary>Save to your phone <span>+</span></summary><div class="settings-body"><p>iPhone: open in <strong>Safari → Share → Add to Home Screen</strong>. Android: use your browser’s <strong>Install app</strong> option.</p><button id="install-button" hidden>Install HYROX Trainer</button><p id="offline-status" class="fine" role="status">Open once online to prepare offline access.</p><button id="update-button" hidden>Refresh to update</button><p class="fine">Progress stays on this device and browser. Home-screen apps may use separate storage on iOS. Back up your plan before switching devices or clearing site data.</p></div></details><footer><strong>HYROX TRAINER</strong><p class="fine">Independent training companion. Not affiliated with HYROX.<br>Use your ticket for your actual race day and division.<br><a href="https://github.com/GithunYd/Hyrox-Trainer">Source & updates</a></p></footer><div id="celebration" role="status" aria-live="polite" class="celebration" hidden></div></main></body></html>`;
fs.writeFileSync('docs/index.html',html);
// Templates are loaded locally and cached offline; the browser dates a copy.
fs.writeFileSync('docs/plan.json',JSON.stringify({schemaVersion:1,weeks:plan},null,2)+'\n');
fs.writeFileSync('docs/manifest.webmanifest',JSON.stringify({id:'./',name:'HYROX Trainer',short_name:'HYROX Trainer',description:'Start today. Train for your race. Check off every win.',lang:'en',start_url:'./',scope:'./',display:'standalone',background_color:'#f6f4ec',theme_color:'#192c26',icons:[{src:'./icons/icon-192.png',sizes:'192x192',type:'image/png',purpose:'any'},{src:'./icons/icon-512.png',sizes:'512x512',type:'image/png',purpose:'any maskable'}]},null,2));
console.log('Built HYROX Trainer with 147 starter sessions and personal race-date setup.');
